### PR TITLE
Add public MSMQ support

### PR DESCRIPTION
**Pull request by hadhh**
Hi @SNikalaichyk 

I update the code to support public MSMQ. Can you have a look at, I guess it would be nice to incorporate this in a new version ?

Tested on W2016

### CODE REVIEW

**Comment by SNikalaichyk** [comment]
Hi @hadhh ,
Looks good, thanks! I really appreciate it. Now I just need to test the new functionality to make sure it doesn't break private queues.

**Comment by SNikalaichyk** [comment]
Hi @hadhh ,
I think we should define a new parameter `QueueType = { Private | Public }`. The default value should be `Private`. Just like the `New-MsmqQueue` cmdlet [does](https://technet.microsoft.com/en-us/library/hh405002(v=vs.85).aspx).
That way we can make sure the new version is backwards compatible.

**Comment by SNikalaichyk** [comment]
Hi @hadhh ,
Please let me know what you think so we can move with this PR.

**Comment by hadhh** [comment]
Hi @SNikalaichyk 

Sorry I was very busy with other stuff. Indeed it makes perfectly sense to do it in the way you propose to allow backwards compatibility.

**Pull request merged**
